---
output: github_document
---

# compeco package

# Exported functions in the `compeco` package as of `r lubridate::today()`

- `ce_convert_rfus()`: Converts input RFUs to concentration
- `ce_prep_rfu_file()`: Prepares input files to get converted into concentration.  Might end up being an internal function
- `ce_process_buoy_data()`: Function to fetch buoy data from newftp.epa.gov and merge into an rda
- `ce_process_exo_data()`: Prepares and combines data files from handheld YSI exo2
- `ce_read_exo_data()`: Reads in an exo data file

# To Do
- On 2022-01-04: Start working on processing rfu file
  - Other things: Add warning when solid standard from sample run is > 5% from curve and then error when difference is gt 10%.  Need to get this from ce_create_std_curve().
  - To prep rfu file:
    - blank correct each file, based on blanks in the data file
    - convert rfu to concentration with calculated std curve
    - convert cuvette concentration back to field concentration
    - trigger for dilutions
  - Double check ours/their fluorometer files to make sure A sample is highest and F sample is lowest. 

- rename input raw data files: instead of multiple dates in file name, use last date for run
  - no: chla_2021_8_11_&_31_&_9_15_&_10_13_&_11_4.csv
  - yes: chla_2021_11_4.csv

# Other ideas
- Maybe: Instead of spec/fluor for std curve internal to package, maybe also allow a user specified file(s) for that calculation.
- Is there a diff between fresh and salt?

## Code of Conduct

Please note that the compeco project is released with a [Contributor Code of Conduct](https://contributor-covenant.org/version/2/0/CODE_OF_CONDUCT.html). By contributing to this project, you agree to abide by its terms.
